### ISSUE TITLE
docker build latest fails if mariadb has been updated

### ISSUE THREAD

**Issue by sunetfreitag** [safespring/nextcloud-db#6]
The current version of MariaDB as declared in https://mirror.one.com/mariadb/repo/10.5/ubuntu/dists/focal/main/binary-amd64/Packages is newer than the version in the Dockerfile. This leads to an error when building latest.

ERROR:
mariadb-server : Depends: mariadb-server-10.5 (>= 1:10.5.6+maria~focal) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

If you update the Dockerfile to 10.5.8, building latest works as expected.

**Comment by ashraf-s9s** [comment]
Hi @sunetfreitag ,

This is expected since the best way to run a Galera Cluster is to have the same version across all nodes, and the best way to track the version changes is by explicitly specifying the minor version in the Docker file at here, https://github.com/safespring/nextcloud-db/blob/master/mariadb/Dockerfile#L47 . 

However, from a practical standpoint, I agree that this could break the Docker image building every time a new minor version comes out. I am giving you some suggestions and let me know which one you think would do better in your process flow:

Option 1:
---------

I could change this line, https://github.com/safespring/nextcloud-db/blob/master/mariadb/Dockerfile#L74, from:
`       "mariadb-server=$MARIADB_VERSION" \`

To:
`      "mariadb-server" \`

So it will always pull the latest 10.5 when building, but it is harder to track the minor version unless we observe the `docker build ...` output, or we could also take a glance at https://mariadb.com/kb/en/changelogs-mariadb-105-series/ and see what is the latest version during the time of image building so we can use the minor version information in the Docker image name.

Option 2:
---------

Stick to the same way, but add a reference in the README documentation file to firstly look at the latest minor version at here: https://mariadb.com/kb/en/changelogs-mariadb-105-series/ 

Then update the Dockerfile on line 47 accordingly, before building the image. 

Regardlessly, my presumption is, wouldn't it be helpful to see the MariaDB minor version in the image name (e.g, `docker build -t safespring/nextcloud-mariadb:10.5.8`) just by doing "docker ps" once the container is running?

Any other suggestions are welcome. Let me know your thoughts on this.

**Comment by gabrielpaues** [comment]
Hi, after some discussions we would like to go with option 1 if its possible to make it as automatic as possible.

**Comment by ashraf-s9s** [comment]
@gabrielpaues @sunetfreitag ,

I have made changes to the Dockerfile to always pull the latest mysql-server's package.

I am going to mark this issue as closed.
